# Generated by Django 5.0.6 on 2024-06-22 07:26
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import social_networking_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("social_networking_app", "0002_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver",
            field=models.ForeignKey(
                help_text="The user who is receiving the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                help_text="The user who sent the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="The current status of the friend request.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("file", models.CharField(max_length=250, null=True)),
                (
                    "feelings",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("bored", "Bored"),
                            ("thrilled", "Thrilled"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=social_networking_app.models.get_image_filename,
                        verbose_name="Image",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_networking_app.post",
                    ),
                ),
            ],
        ),
    ]
